import type { TrelloViewState } from './TrelloViewState.ts'
import { getAssetBaseUrl } from './AssetBaseUrl.ts'

export const createInitialState = (): TrelloViewState => {
  return {
    activeSearchQuery: '',
    addingCardLabelId: '',
    addingCardListId: '',
    addingList: false,
    baseUrl: getAssetBaseUrl(import.meta.url),
    boardBackgroundEnabled: false,
    boardDetail: undefined,
    boardLabels: [],
    boardLabelsLoaded: false,
    boardLabelsLoading: false,
    boards: [],
    cardAttachmentsLoading: false,
    cardCommentsLoading: false,
    cardDetailLoading: false,
    cardDetailLoadingCardId: '',
    cardDetailResizeStartWidth: 360,
    cardDetailResizeStartX: 0,
    cardDetailWidth: 360,
    cardLabelPickerOpen: false,
    context: {},
    contextMenuCardId: '',
    contextMenuListId: '',
    coverImageUrls: {},
    credentials: undefined,
    draftApiKey: '',
    draftCardDescription: '',
    draftCardTitle: '',
    draftComment: '',
    draftLabelSearchQuery: '',
    draftListTitles: {},
    draftNewCardTitle: '',
    draftNewListTitle: '',
    draftSearchQuery: '',
    draftToken: '',
    draggedCardId: '',
    dragTargetListId: '',
    editingCardDescription: false,
    editingCardTitle: false,
    error: '',
    focusedName: '',
    loading: false,
    movingCardId: '',
    pendingSelections: [],
    recentBoardViews: [],
    resizingCardDetail: false,
    savingCardDetail: false,
    savingComment: false,
    savingNewCard: false,
    savingNewList: false,
    searchEnabled: false,
    searchResults: [],
    selectedCardDetail: undefined,
    writingComment: false,
  }
}
